/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        slate: {
          50: '#f8f7f3',
          100: '#efede7',
          200: '#dcd8cf',
          300: '#c7c3bb',
          400: '#9f9b92',
          500: '#7f7b74',
          600: '#625f59',
          700: '#484641',
          800: '#2b2a27',
          900: '#171716',
          950: '#080808',
        },
        brand: {
          50: '#f7f5ef',
          100: '#e8e5dc',
          200: '#d6d2c8',
          300: '#b9b5ab',
          400: '#959188',
          500: '#76736c',
          600: '#4b4a46',
          700: '#353430',
          800: '#2b2a27',
          900: '#232321',
          950: '#111110',
        },
        canvas: 'var(--canvas)',
        foreground: 'var(--foreground)',
        primary: 'var(--primary)',
        'primary-foreground': 'var(--primary-foreground)',
        'accent-soft': 'var(--accent-soft)',
        violet: 'var(--violet)',
        success: 'var(--success)',
        'bg-primary-dark': 'var(--canvas)',
        'bg-surface-dark': 'var(--surface)',
        'text-primary': 'var(--foreground)',
        'text-secondary': 'var(--muted-foreground)',
        'text-muted': 'var(--muted-foreground)',
        'border-subtle': 'var(--border)',
        'accent-blue': 'var(--primary)',
        'accent-cyan': 'var(--primary)',
      },
      fontFamily: {
        sans: ['var(--font-inter)', 'system-ui', 'sans-serif'],
        display: ['var(--font-plus-jakarta)', 'system-ui', 'sans-serif'],
        mono: ['var(--font-jetbrains-mono)', 'monospace'],
      },
      boxShadow: {
        card: '0 18px 45px -30px rgb(17 18 20 / 0.34)',
        'card-hover': '0 24px 60px -32px rgb(255 145 56 / 0.24)',
        'card-sm': '0 8px 24px -18px rgb(15 23 42 / 0.3)',
      }
    },
  },
  plugins: [],
};
