/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // New UI Tech Theme Colors from new-ui/page.js
        'primary-container': '#06b6d4',
        'surface-container': '#171f33',
        'on-secondary': '#3c0091',
        'on-secondary-container': '#c4abff',
        'primary-fixed': '#acedff',
        'error': '#ffb4ab',
        'on-primary-container': '#00424f',
        'on-primary-fixed': '#001f26',
        'on-tertiary-fixed-variant': '#6a3b00',
        'on-surface': '#dae2fd',
        'tertiary-fixed': '#ffdcbf',
        'surface-container-low': '#131b2e',
        'secondary-container': '#571bc1',
        'on-tertiary': '#4b2800',
        'outline-variant': '#3d494c',
        'tertiary-fixed-dim': '#ffb873',
        'on-primary-fixed-variant': '#004e5c',
        'primary': '#4cd7f6',
        'surface-container-high': '#222a3d',
        'inverse-on-surface': '#283044',
        'on-tertiary-container': '#5b3200',
        'surface': '#0b1326',
        'surface-tint': '#4cd7f6',
        'inverse-primary': '#00687a',
        'on-primary': '#003640',
        'on-error': '#690005',
        'surface-bright': '#31394d',
        'surface-variant': '#2d3449',
        'tertiary': '#ffb873',
        'surface-container-highest': '#2d3449',
        'primary-fixed-dim': '#4cd7f6',
        'surface-dim': '#0b1326',
        'secondary-fixed-dim': '#d0bcff',
        'on-secondary-fixed-variant': '#5516be',
        'secondary-fixed': '#e9ddff',
        'on-error-container': '#ffdad6',
        'secondary': '#d0bcff',
        'tertiary-container': '#e89337',
        'on-secondary-fixed': '#23005c',
        'on-background': '#dae2fd',
        'error-container': '#93000a',
        'outline': '#869397',
        'on-tertiary-fixed': '#2d1600',
        'background': '#0b1326',
        'inverse-surface': '#dae2fd',
        'on-surface-variant': '#bcc9cd',
        'surface-container-lowest': '#060e20',
      },
      borderRadius: {
        'DEFAULT': '0.125rem',
        'lg': '0.25rem',
        'xl': '0.5rem',
        'full': '0.75rem'
      },
      spacing: {
        'margin-desktop': '80px',
        'unit': '4px',
        'margin-mobile': '20px',
        'gutter': '24px',
        'container-max': '1280px'
      },
      fontFamily: {
        'code-sm': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif']
      },
      fontSize: {
        'code-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '1.4', fontWeight: '500' }],
        'label-caps': ['12px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '500' }],
        'headline-lg': ['40px', { lineHeight: '1.2', fontWeight: '600' }],
        'headline-lg-mobile': ['32px', { lineHeight: '1.2', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }]
      },
      boxShadow: {
        // New UI shadows (glow effects)
        'glow': '0 0 20px rgba(6, 182, 212, 0.2)',
        'glow-violet': '0 0 20px rgba(196, 171, 255, 0.2)',
        'glow-active': '0 0 15px rgba(6, 182, 212, 0.5)',
      }
    },
  },
  plugins: [],
};