-- Client portal foundation.
-- Portal access is granted explicitly by an administrator after an engagement begins.

create table if not exists public.client_accounts (
  user_id uuid primary key references auth.users(id) on delete cascade,
  company_name text,
  portal_enabled boolean not null default false,
  onboarding_stage text not null default 'invited'
    check (onboarding_stage in ('invited', 'onboarding', 'active', 'paused', 'completed')),
  activated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_projects (
  id uuid primary key default gen_random_uuid(),
  client_id uuid not null references public.client_accounts(user_id) on delete cascade,
  project_code text not null unique,
  name text not null,
  summary text,
  status text not null default 'planning'
    check (status in ('planning', 'in_progress', 'review', 'on_hold', 'completed')),
  progress smallint not null default 0 check (progress between 0 and 100),
  next_milestone text,
  target_launch date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.client_project_updates (
  id bigint generated by default as identity primary key,
  project_id uuid not null references public.client_projects(id) on delete cascade,
  title text not null,
  summary text,
  created_at timestamptz not null default now()
);

create index if not exists client_projects_client_id_idx
  on public.client_projects (client_id, updated_at desc);
create index if not exists client_project_updates_project_id_idx
  on public.client_project_updates (project_id, created_at desc);

alter table public.client_accounts enable row level security;
alter table public.client_projects enable row level security;
alter table public.client_project_updates enable row level security;

grant select on public.client_accounts, public.client_projects, public.client_project_updates to authenticated;
grant insert, update, delete on public.client_accounts, public.client_projects, public.client_project_updates to authenticated;
grant usage, select on sequence public.client_project_updates_id_seq to authenticated;

drop policy if exists client_accounts_read on public.client_accounts;
create policy client_accounts_read on public.client_accounts for select to authenticated
using (user_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists client_accounts_admin_insert on public.client_accounts;
create policy client_accounts_admin_insert on public.client_accounts for insert to authenticated
with check ((select private.is_admin()));
drop policy if exists client_accounts_admin_update on public.client_accounts;
create policy client_accounts_admin_update on public.client_accounts for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists client_accounts_admin_delete on public.client_accounts;
create policy client_accounts_admin_delete on public.client_accounts for delete to authenticated
using ((select private.is_admin()));

drop policy if exists client_projects_read on public.client_projects;
create policy client_projects_read on public.client_projects for select to authenticated
using (
  (client_id = (select auth.uid()) and exists (
    select 1 from public.client_accounts account
    where account.user_id = (select auth.uid()) and account.portal_enabled
  )) or (select private.is_admin())
);

drop policy if exists client_projects_admin_insert on public.client_projects;
create policy client_projects_admin_insert on public.client_projects for insert to authenticated
with check ((select private.is_admin()));
drop policy if exists client_projects_admin_update on public.client_projects;
create policy client_projects_admin_update on public.client_projects for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists client_projects_admin_delete on public.client_projects;
create policy client_projects_admin_delete on public.client_projects for delete to authenticated
using ((select private.is_admin()));

drop policy if exists client_project_updates_read on public.client_project_updates;
create policy client_project_updates_read on public.client_project_updates for select to authenticated
using (
  exists (
    select 1
    from public.client_projects project
    join public.client_accounts account on account.user_id = project.client_id
    where project.id = client_project_updates.project_id
      and project.client_id = (select auth.uid())
      and account.portal_enabled
  ) or (select private.is_admin())
);

drop policy if exists client_project_updates_admin_insert on public.client_project_updates;
create policy client_project_updates_admin_insert on public.client_project_updates for insert to authenticated
with check ((select private.is_admin()));
drop policy if exists client_project_updates_admin_update on public.client_project_updates;
create policy client_project_updates_admin_update on public.client_project_updates for update to authenticated
using ((select private.is_admin())) with check ((select private.is_admin()));
drop policy if exists client_project_updates_admin_delete on public.client_project_updates;
create policy client_project_updates_admin_delete on public.client_project_updates for delete to authenticated
using ((select private.is_admin()));

drop trigger if exists set_client_accounts_updated_at on public.client_accounts;
create trigger set_client_accounts_updated_at before update on public.client_accounts
for each row execute function private.set_updated_at();

drop trigger if exists set_client_projects_updated_at on public.client_projects;
create trigger set_client_projects_updated_at before update on public.client_projects
for each row execute function private.set_updated_at();
